# Jenkins 설정
jenkins:
  controller:
    # Jenkins 이미지 설정
    image: "jenkins/jenkins"
    tag: "2.426.1-lts"
    imagePullPolicy: IfNotPresent

    # 종료 메시지 설정
    terminationMessagePath: /Users/mini/Documents/logs/infra/jenkins/termination-log
    terminationMessagePolicy: FallbackToLogsOnError

    # 추가 볼륨 마운트
    extraVolumeMounts:
      - name: logs
        mountPath: /Users/mini/Documents/logs/infra/jenkins
    
    # 추가 볼륨
    extraVolumes:
      - name: logs
        hostPath:
          path: /Users/mini/Documents/logs/infra/jenkins
          type: DirectoryOrCreate

    # 관리자 계정 설정
    adminUser: "admin"
    adminPassword: "admin123"  # 실제 배포 시 반드시 변경

    # 서비스 설정
    serviceType: NodePort
    servicePort: 8080
    targetPort: 8080
    nodePort: 30800

    # 인그레스 설정
    ingress:
      enabled: true
      ingressClassName: nginx
      hostName: jenkins.local
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"

    # 영구 볼륨 설정
    persistence:
      enabled: true
      storageClass: "standard"
      size: "10Gi"
      accessMode: "ReadWriteOnce"
      annotations: {}

    # 시스템 메시지
    systemMessage: "Jenkins on Kubernetes"

    # 초기화 설정
    initContainerEnv:
      - name: JENKINS_HOME
        value: /var/jenkins_home
    
    # 컨테이너 설정
    containerEnv:
      - name: JENKINS_OPTS
        value: "--prefix=/jenkins"
      - name: JAVA_OPTS
        value: >-
          -Xmx2g
          -Xms512m
          -XX:+UnlockExperimentalVMOptions
          -XX:+UseCGroupMemoryLimitForHeap
          -Djenkins.install.runSetupWizard=false
          -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-scripts; default-src 'self'; style-src 'self' 'unsafe-inline';"

    # 초기 플러그인 설치
    installPlugins:
      - kubernetes:4148.v47a_66d95a_1d0
      - workflow-aggregator:596.v8c21c963d92d
      - git:5.2.1
      - configuration-as-code:1775.v810dc950b_514
      - docker-workflow:572.v950f58993843
      - docker-plugin:1.5
      - kubernetes-cli:1.12.1
      - job-dsl:1.87
      - pipeline-utility-steps:2.16.1
      - blueocean:1.27.7

    # 리소스 제한
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2000m"
        memory: "4Gi"

    # 프로브 설정
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5

    # 보안 설정
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
      allowPrivilegeEscalation: false

    # JCasC 설정
    JCasC:
      defaultConfig: true
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: Welcome to Jenkins on Kubernetes!
            numExecutors: 0
            mode: EXCLUSIVE
            securityRealm:
              local:
                allowsSignup: false
                users:
                  - id: "${adminUser}"
                    password: "${adminPassword}"
        cloud-config: |
          jenkins:
            clouds:
              - kubernetes:
                  name: "kubernetes"
                  serverUrl: "https://kubernetes.default"
                  namespace: "${POD_NAMESPACE}"
                  jenkinsUrl: "http://jenkins-controller:8080"
                  jenkinsTunnel: "jenkins-agent:50000"
                  podLabels:
                    - key: "jenkins/jenkins-controller"
                      value: "true"
                  containerCapStr: "10"
                  podRetention: "never"
                  maxRequestsPerHostStr: "32"
                  waitForPodSec: "60"

  # 에이전트 설정
  agent:
    enabled: true
    componentName: "jenkins-agent"
    image: "jenkins/inbound-agent"
    tag: "3107.v665000b_51092-5"
    
    # 에이전트 종료 메시지 설정
    terminationMessagePath: /Users/mini/Documents/logs/infra/jenkins-agent/termination-log
    terminationMessagePolicy: FallbackToLogsOnError

    # 에이전트 추가 볼륨 마운트
    extraVolumeMounts:
      - name: agent-logs
        mountPath: /Users/mini/Documents/logs/infra/jenkins-agent

    # 에이전트 추가 볼륨
    extraVolumes:
      - name: agent-logs
        hostPath:
          path: /Users/mini/Documents/logs/infra/jenkins-agent
          type: DirectoryOrCreate

    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    
    # 에이전트 보안 설정
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

  # 네트워크 정책
  networkPolicy:
    enabled: true
    apiVersion: networking.k8s.io/v1
    internalAgents:
      allowed: true
      podLabels:
        jenkins/jenkins-agent: "true"
    externalAgents:
      enabled: false 