{{- if .Values.springboot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-springboot
  labels:
    app: springboot
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.springboot.service.type }}
  ports:
    - port: {{ .Values.springboot.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: springboot
    release: {{ .Release.Name }}
{{- end }} 