{{- if .Values.registry.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-registry-pvc
  labels:
    app: registry
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.registry.persistence.accessMode | quote }}
  storageClassName: {{ .Values.registry.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.registry.persistence.size | quote }}
{{- end }} 