{{- if .Values.registry.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-auth
  labels:
    app: registry
    release: {{ .Release.Name }}
type: Opaque
data:
  # htpasswd -Bbn username password
  htpasswd: {{ htpasswd .Values.registry.auth.username .Values.registry.auth.password | b64enc }}
{{- end }} 