apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    app: registry
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - port: {{ .Values.registry.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: registry
    release: {{ .Release.Name }} 